# Generated from config/configVariables.ts

project_id = "antonarbus"
project_number = "850593405209"
github_repository = "antonarbus/antonarbus.com"
bucket_for_terraform_state_name = "antonarbus-terraform-state"
region = "us-central1"
artifact_registry_name = "docker-images"
docker_image_name = "web-app"
github_actions_sa_name = "github-actions-sa"
cloud_run_sa_name = "cloud-run-sa"
min_instances = "0"
max_instances = "5"
cpu_limit = "1"
memory_limit = "512Mi"
container_port = "8080"
cloud_run_service_name = "web-app-dev"
custom_domain = "dev.antonarbus.com"
environment = "dev"
