/**
 * Generate .tfvars files from TypeScript config
 *
 * This script ensures that .tfvars files stay in sync with the TypeScript config.
 * Run this after modifying config/configVariables.ts
 */

import { resolve } from 'path'
import { configVariables } from '../../config/configVariables'
import { logger } from '../lib/output'

// Convert camelCase to snake_case
function toSnakeCase(str: string): string {
  return str.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`)
}

// Generate a .tfvars file content from config object
function generateTfvarsContent(env: string, config: Record<string, string>): string {
  const header = `# ==============================================================================
# ${env.toUpperCase()} ENVIRONMENT CONFIGURATION
# ==============================================================================
# This file is GENERATED from config/configVariables.ts
# DO NOT EDIT THIS FILE DIRECTLY - Edit config/configVariables.ts instead
#
# To regenerate this file:
#   bun run generate-tfvars
#
# IMPORTANT: This file should be committed to git (no secrets here!)
# ==============================================================================

# PROJECT & REGION

`

  const lines: string[] = []
  const entries = Object.entries(config)

  // Group shared values
  const shared = ['projectId', 'projectNumber', 'region', 'bucketForTerraformStateName']
  const artifactRegistry = ['artifactRegistryName', 'dockerImageName']
  const cloudRun = ['cloudRunServiceName']
  const serviceAccounts = ['githubActionsSaName', 'cloudRunSaName']
  const scaling = ['minInstances', 'maxInstances', 'cpuLimit', 'memoryLimit', 'containerPort']
  const domain = ['customDomain']

  // Helper to add entries
  const addEntries = (keys: string[], label?: string) => {
    if (label) lines.push(`# ${label}\n`)
    for (const key of keys) {
      const entry = entries.find(([k]) => k === key)
      if (entry) {
        const [k, v] = entry
        const snakeKey = toSnakeCase(k)
        const paddedKey = snakeKey.padEnd(31)
        lines.push(`${paddedKey} = "${v}"`)
      }
    }
    lines.push('')
  }

  addEntries(shared)
  addEntries(artifactRegistry, 'ARTIFACT REGISTRY (SHARED across all environments)')
  addEntries(cloudRun, 'CLOUD RUN (environment-specific)')
  addEntries(serviceAccounts, 'SERVICE ACCOUNTS (SHARED across all environments)')
  addEntries(scaling, 'SCALING & PERFORMANCE')
  addEntries(domain, 'CUSTOM DOMAIN')

  return header + lines.join('\n')
}

async function main() {
  logger.section('Generating .tfvars files from TypeScript config...')
  logger.emptyLine()

  const configDir = resolve(__dirname, '../../config')

  for (const [env, config] of Object.entries(configVariables)) {
    const filePath = resolve(configDir, `${env}.tfvars`)
    const content = generateTfvarsContent(env, config as Record<string, string>)

    await Bun.write(filePath, content)
    logger.success(`Generated ${env}.tfvars`)
  }

  logger.emptyLine()
  logger.success('All .tfvars files generated successfully!')
  logger.info('Files are ready to commit to git')
}

main().catch((error) => {
  logger.error('Failed to generate .tfvars files')
  console.error(error)
  process.exit(1)
})
